### ISSUE TITLE
Representing a union of a record and an enum

### ISSUE THREAD

**Issue by keirlawson** [avro-kotlin/avro4k#101]
I have a schema that includes the below type:

```
{
    "name" : "operation",
    "type" : [ {
      "type" : "record",
      "name" : "OperationOnEntry",
      "fields" : [ ... ]
    }, {
      "type" : "enum",
      "name" : "Read",
      "symbols" : [ "Read" ]
    } ]
  }
```

Is it possible to represent this type in Kotlin using Avro4k? I tried

```kotlin
@Serializable
sealed class Operation
@Serializable
data class OperationOnEntry( ... ) : Operation()
@Serializable
object Read : Operation()
```

However this produces

```
{
    "name" : "operation",
    "type" : [ {
      "type" : "record",
      "name" : "OperationOnEntry",
      "fields" : [ ... ]
    }, {
      "type" : "record",
      "name" : "Read",
      "fields" : [ ]
    } ]
  }
```

**Comment by thake** [comment]
Right now this is afaik not possible to represent. Avro4k does currently not support open polymorphic references (see https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#open-polymorphism). 

This would be needed to serialize the following data structure which would matches the first mentioned schema:
```kotlin
interface Operation
@Serializable
data class OperationOnEntry( ... ) : Operation
@Serializable
enum class Read : Operation {
    Read
}
```

**Comment by thake** [comment]
This is now possible with the support of polymorphic classes #110
