### ISSUE TITLE
Android and multiplatform

### ISSUE THREAD

**Issue by mcpiroman** [avro-kotlin/avro4k#128]
Hi, 
does this library work on Android? It'd be nice to document it.

Also, would it be theoretically possible to support JS/native targets? Avro does have C library and there is https://github.com/mtth/avsc for JS FWIW.

**Comment by thake** [comment]
It currently does not support JS/native targets. It should be usable on android. I wouldn't know of anything that speaks against using it on android.

**Comment by Chuckame** [comment]
Closing stale issue as won't do for the moment. Don't hesitate to 👍 the original message to see the community needs 🚀

**Comment by thake** [comment]
Planned to be tackled in version 2.

**Comment by Chuckame** [comment]
Seems maybe too early to talk about real multiplatform. Let's discuss to prioritize features 🚀

**Comment by Chuckame** [comment]
Android is theorically compatible as the apache avro library is compatible. For js/wasm/native support, please look at https://github.com/avro-kotlin/avro4k/issues/207 and put a 👍 if you want it.
