### ISSUE TITLE
Gradle task to generate schema definitions 

### ISSUE THREAD

**Issue by AmsterdamFilho** [avro-kotlin/avro4k#134]
It is already possible to see the schemas for a class: 
```
val schema = Avro.default.schema(Pizza.serializer())
println(schema.toString(true))
```
It would be very useful to create a gradle task that scans all serializable classes and put their schemas in the generated sources directory of the project. This could be used in the CI process to send them to schema registry.

**Comment by Chuckame** [comment]
What about calling this code from a custom job in gradle (kts?), can it work?

**Comment by Chuckame** [comment]
Hello, avro4k is not a gradle or maven plugin for today, so we won't implement this unless someone makes a PR or another library to have this feature.
