### ISSUE TITLE
Is it possible to serialize to GenericRecord without a SerializationStrategy<T>?

### ISSUE THREAD

**Issue by minionOfZuul** [avro-kotlin/avro4k#136]
I have a use case where I need to work strictly with GenericRecords - in other words, I have no data class from which to derive a serializer. I've combed through the docs and the API and I don't see a straightforward way to give Avro4k an instance and a schema and get back a GenericRecord. Is there such a thing?

**Comment by thake** [comment]
If you don't have an @Serializable annotated data class, you'll have to provide a custom serializer so that kotlinx.serialization knows how to serialize the provided instance.

Does this help you? Maybe I have got your question wrong. Maybe you can give some pseudo code of what you want to achieve.

**Comment by minionOfZuul** [comment]
Thanks for the reply. I'm still getting my feet wet when it comes to Avro, so forgive
