### ISSUE TITLE
Update de/serialization examples in README 

### ISSUE THREAD

**Issue by jangalinski** [avro-kotlin/avro4k#137]
I am trying to use avro4k, but I am struggling with the usage.

it seems that the examples in the README do not reflect the current state of the lib anymore.

It says I could use

`val os = AvroOutputStream.binary(schema, Pizza.serializer()).to(File("pizzas.avro"))`

and 

`val input = AvroInputStream.binary(Pizza.serializer(), schema).from(File("pizzas.avro"))`

but there is no static function `binary` in either of those streams.

Could you please update the docs?

**Comment by thake** [comment]
@jangalinski, thanks for raising this issue! Indeed, the code examples were outdated. I've updated them.
