### ISSUE TITLE
Support avro single object encoding

### ISSUE THREAD

**Issue by jangalinski** [avro-kotlin/avro4k#141]
Currently, the README states that single object encoding is not supported.

Following up on the discussion in #138, I believe this should be possible to implement.

From the [Specification](https://avro.apache.org/docs/1.11.1/specification/#single-object-encoding-specification):

Single Avro objects are encoded as follows:

> 1. A two-byte marker, C3 01, to show that the message is Avro and uses this single-record format (version 1).
> 1. The 8-byte little-endian CRC-64-AVRO [fingerprint](https://avro.apache.org/docs/1.11.1/specification/#schema-fingerprints) of the object’s schema.
> 1. The Avro object encoded using [Avro’s binary encoding](https://avro.apache.org/docs/1.11.1/specification/#binary-encoding).

Binary encoding is already supported, and the fingerprint of the schema should be accessible from 

`SchemaNormalization.parsingFingerprint64(Avro.default.schema(MySerializableDataClass.serializer()))`

so serialization should come down to concatenating  bytes.

For deserialization, we need to deconstruct the single object encoded byte array, check the first two marker bytes, extract the fingerprint, lookup the writer schema from a `SchemaStore` and decode the remaining binary payload to GenericRecord and then to the target data class.

**Comment by jangalinski** [comment]
I will try to provide this feature.

**Comment by jangalinski** [comment]
see #142 142

**Comment by Chuckame** [comment]
Hello, after some work at revamping the `Avro` api #186 (WIP), there is a new easier and promising way of implementing the single object (for the moment, named serialization delegate). The avro input and output stream would be removed. Don't hesitate to comment it as you worked hard to integrate this single object format in the current version of avro4k.

Thanks for being patient and sorry for the delay again.
