### ISSUE TITLE
Document release workflow

### ISSUE THREAD

**Issue by thake** [avro-kotlin/avro4k#143]
The release workflow is currently not documented. It should result in a CONTRIBUTING.md.

**Comment by Chuckame** [comment]
Can you quickly sumup the current procedure? Or by default, I would say: f
- when pr merged, make a release (tag + github release)
- when multi pr needed to have a complete feature, then merge into a separate branch, and when all Il merge in this branch, then merge it in main branch

For versioning, let's focus on the library API (public methods dedicated to users) :
- patch increment for non-breaking, non-new features, fixes of unexpected behaviors or dependency update that don't change the current behavior (e.g. For changing something inside method body, while not changing methods params, params names, methods names, class names, package names) 
- minor increment for new features (not changing current behaviors except when the behavior change is directly linked to a new param, adding method param with a default value that should replicate the same behavior as before, adding property/method/class) 
- major increment for removing/renaming stuff and dependency update that change the current behavior 

What do you think?

**Comment by Chuckame** [comment]
Please also indicate how you are publishing a new version (or it's automatic when release or tag created?)

**Comment by Chuckame** [comment]
Found it, just create the release, then execute `release` workflow inside github actions tab onto the created tag during release
