### ISSUE TITLE
Improve release process

### ISSUE THREAD

**Issue by Chuckame** [avro-kotlin/avro4k#150]
## Currently
To release, we have to:
- create the release (that is creating the tag)
- execute a release action with the tag name previously created
Also, there is no documentation on it

## What we could do
Just create the release (that is creating the tag, that is triggering the publish action)

And document it inside a README or a CONTRIBUTING

**Comment by thake** [comment]
hey @Chuckame, sorry for letting you wait so long. I've changed the release job to automatically publish **and stage** the repository to maven central. This was not the case before. One had to stage and close the repository manually in the sonatype oss nexus. 

Additionally, the GitHub release documentation & Git tag will now be created automatically.

**Comment by thake** [comment]
This issue has been implemented with 3d64d549fefcf96aede9a711007a7c16bb024823, 32a0f653085e0d47f206ea3c0e2015d3b5462996, c2753ac26c5013e020a013bc41ece94e86c6e4f4, and 0f0a1515463d33e51a6b5d6085ec1b814e7489bb
