### ISSUE TITLE
Cache Schemas for classes

### ISSUE THREAD

**Issue by thake** [avro-kotlin/avro4k#159]
Add caching for the deducted Avro schemas to the library itself. The implementation of the cache must be thread-safe. A possible JVM-dependent way would be to use `ClassValue` as it is implemented in Avro's `ClassValueCache`.

Preferrable, the implementation should not depend on JVM specifics so that making this library multiplatform in the future is easier.

**Comment by Chuckame** [comment]
Done in #190

**Comment by Chuckame** [comment]
Released in [v2.0.0](https://github.com/avro-kotlin/avro4k/releases/tag/v2.0.0)
