### ISSUE TITLE
Beautify the Avro api entrypoint

### ISSUE THREAD

**Issue by Chuckame** [avro-kotlin/avro4k#163]
Currently, to do common stuff, we have to start by `Avro.default`. But when we want to override defaults, we do like this:
```kotlin
Avro(SerializersModule {
    contextual(...)
}, AvroConfiguration(
    namingStrategy = ...
))
```

kolinx serialization Json (and other official supported formats) are doing very interesting stuff, here the examples:
```kotlin
// default way
Json.encodeToByteArray(...)

// customized way
Json {
   serializersModule = SerializersModule {
    contextual(...)
   }
    namingStrategy = ...
}.encodeToByteArray(...)
```

It would be great to do it ! It's not that complex to implement, it's mainly copy/paste from [Json class](https://github.com/Kotlin/kotlinx.serialization/blob/master/formats/json/commonMain/src/kotlinx/serialization/json/Json.kt)

**Comment by thake** [comment]
I think this is a good starting point for our API remake that is required for moving avro4k to multiplatform :rocket:

**Comment by thake** [comment]
@Chuckame, can you make a draft in a PR? It does not have to compile, just to showcase how the API would look like.

**Comment by Chuckame** [comment]
Done in #186
