### ISSUE TITLE
Use Kotlinx.Serialization BinaryFormat Interface

### ISSUE THREAD

**Issue by SmarTTYs** [avro-kotlin/avro4k#223]
Hi in advance, thanks for the great work in avro4k 2.0 so far.

**Is your feature request related to a problem? Please describe.**
I am currently developing a simple library at my workplace which also contains some bindings between the java kafka library and kotlinx.serialization. This library provides the ability to use Kotlin.serialization BinaryFormat's in order to create Headers and Serializers / Deserializers. I want the core of the library to be as abstract as possible (in the scope of Kotlin.serialization) and therefor I don't want to provide any specific format implementation (like avro4k). The user should decide whether to use Protobuf / Avro or what ever binary representation for their encoding / decoding. The 1.0 of Avro4k used Kotlin.serialization's BinaryFormat interface which allowed me to access extensions functions defined in kotlinx.serialization core.

**Describe the solution you'd like**
Avro4k 2.0 should implement the BinaryFormat like the other binary formats (f.e. Protobuf) do.

**Describe alternatives you've considered**
Currently I am wrapping an Avro instance like this:
```kotlin
open class AvroBinary(private val avro: Avro) : BinaryFormat {
    override val serializersModule: SerializersModule
        get() = avro.serializersModule

    override fun <T> encodeToByteArray(serializer: SerializationStrategy<T>, value: T): ByteArray {
        val schema = avro.schema(serializer.descriptor)
        return avro.encodeToByteArray(schema, serializer, value)
    }

    override fun <T> decodeFromByteArray(deserializer: DeserializationStrategy<T>, bytes: ByteArray): T {
        val schema = avro.schema(deserializer.descriptor)
        return avro.decodeFromByteArray(schema, deserializer, bytes)
    }

    companion object Default : AvroBinary(Avro)
}
```

**Additional context**
As the Avro-schema gets constructed by passing a SerialDescriptor instance it should not be very hard to implement the interface. Of course, I am also willing to open a PR with the required changes :)

**Comment by Chuckame** [comment]
I've did it, wait for the next release candidate. Do you also have some feedback regarding the avro4k v2 release?

**Comment by Chuckame** [comment]
Has been released in 2.0.0-rc6

**Comment by SmarTTYs** [comment]
Hi
Thanks for the quick implementation! :)

I am currently testing out the new Avro4k 2.0 release candidates and I am very happy with the changes so far. 
If I notice anything, I will of course open an issue.

This issue can be closed for all I care

**Comment by Chuckame** [comment]
Thanks, I'll close it when v2 is released (not in release candidate).
