### ISSUE TITLE
Spring Cloud Stream Integration

### ISSUE THREAD

**Issue by frne** [avro-kotlin/avro4k#244]
**Is your feature request related to a problem? Please describe.**
Using Spring Cloud Stream with Kafka and Avro still relies on the old maven plugin, generating java classes from avro schemas. With gradle, it even needs a custom task implementation to generate java source from avro schemas.

**Describe the solution you'd like**
Would be nice, if this library was usable with Spring Cloud Stream (and Confluent Schema Registry). Mabe this is even possible and it just needs documentation...

**Describe alternatives you've considered**
Alternative is using the old generated java classes.

**Additional context**
- An example of hot to use Spring Cloud Stream with Kotlin can be found here: https://github.com/spring-cloud/spring-cloud-stream-samples/tree/main/kafka-e2e-kotlin-sample

**Comment by Chuckame** [comment]
I'm a bit lost. You are expecting avro4k to be working with spring cloud stream, but also supporting the confluent SR and also generate classes, please check first the existing issues, then open the according issues for each specific demand or open a discussion. Avro4k is intended to be as generic as possible, the reason why we don't bundle such specific serializer. However, there are some common usage, by example serializing avro in kafka events using the confluent schema registry. Those common usage may lead to adding other packages (follow this for kafka + SR #218).

There is no blocker about using this library in any framework, but for sure it needs adaptation to fit the framework. For serializing specific avro content in spring cloud stream (but without confluent SR), you should create your (de)serializer which would use `Avro.encodeToByteArray` or `Avro.decodeToByteArray`. Then you just need to configure your binder using this serializer.

Also, you are talking about generated java source while this library is for kotlin sources. Let's suppose you want kotlin source generation, then please check #212 

Still, thanks for the interest for this library, and don't hesitate to a PR to add a guide on how to use it in spring cloud stream 🚀

**Comment by Chuckame** [comment]
I'll still repeat a detail, we are planning to support code generation and confluent/kafka serializers, which would allows you to be used with spring cloud stream! 😁
