### ISSUE TITLE
when will next avro4k be release ?  

### ISSUE THREAD

**Issue by xmlking** [avro-kotlin/avro4k#69]
when will next avro4k be release with `kotlinx.serialization` version 1.0.0-RC support. 
I am blocked as I upgraded to kotlin 1.4.
is there a way I can pull the latest build?

**Comment by keithhawkridge** [comment]
fyi... https://github.com/avro-kotlin/avro4k/pull/66#issuecomment-684756661

**Comment by sksamuel** [comment]
0.40.0 has been released.
