### ISSUE TITLE
 New avro4k release - upgrade kotlinx.serialization to 1.0.0 etc

### ISSUE THREAD

**Issue by kossi** [avro-kotlin/avro4k#74]
First stable release of `kotlinx.serialization` has been released. avro4k should be upgrade to it or probably none/minor changes 

https://github.com/Kotlin/kotlinx.serialization/releases/tag/v1.0.0

EDIT: Oh sorry versions are upgrade already in this commit:  https://github.com/avro-kotlin/avro4k/commit/b38560f83cae881b9a0031da5c95744b7578e981 by @thake . Well perhaps time for new release of avro4k ? EDIT v2 perhaps it was after this issue

P.S. I noticed that this Github repository is missing tags from latest releases. Or at least after project transferred to use GH actions. So probably missing from its definitions.

**Comment by thake** [comment]
@kossi you were right. I created the commit after the issue has been created. I forgot to mention this issue in the commit message. I'm currently still working on a refactoring of the Avro API that should be part of the release. Shouldn't take too long.

**Comment by thake** [comment]
@kossi took a little bit longer. The release 0.41.0 is now available.

**Comment by kossi** [comment]
Great, and now with even git tag. Thanks!

**Comment by geomagilles** [comment]
Thx :)
