### ISSUE TITLE
Create tag within release workflow

### ISSUE THREAD

**Issue by thake** [avro-kotlin/avro4k#86]
Currently no tag is created during the release workflow. This should be intregrated to minimize maintanance effort.

**Comment by jangalinski** [comment]
Side note: The 1.8.0 tag is missing, it is quite confusing when you enter the repo that on the right the latest release is 1.7 while the latest maven central is 1.8.0 ... maybe manually add the release tag?

**Comment by thake** [comment]
@jangalinski thanks! I've added it manually.
