### ISSUE TITLE
Could it support generate data classes from avsc file?

### ISSUE THREAD

**Issue by msampaioatbigw** [avro-kotlin/avro4k#96]

**Comment by kossi** [comment]
Isn't that a bit out-of-scope of this project? Anyways @thake have made this project that you could use: https://github.com/thake/avro4k-compiler

Or just use avro java libs to read schema files  and generate from those schemas kotlin data classes with https://square.github.io/kotlinpoet/ for an example.  From my personal experiences kotlinpoet have quite neat API for generating kotlin classes compared to templating. 

Probably in the end it doesn't really matter and code generating can be really use-case / project specific if you wan't enrich those generated classes with certain interfaces or metadata.  Anyways probably better to do it yourself?

**Comment by thake** [comment]
@msampaioatbigw: Closing this issue as this is out of scope. 

As already pointed out by @kossi you can take a look at https://github.com/thake/avro4k-compiler which is actually another project of mine. If you have any questions / issues with it, you can raise a issue there.
